#http {
#  server {
#    listen 80;
#    server_name mydomain.me;
#
#    location / {
#      return 301 https://$host$request_uri;
#    }
#  }
#  server {
#    listen 443 ssl;
#    ssl_certificate /etc/nginx/ssl/mydomain_me_chain.crt;
#    ssl_certificate_key /etc/nginx/ssl/mydomain.me.key;
#    server_name mydomain.me;
#
#    # Route to nipple-05
#    location /.well-known {
#      proxy_pass http://nipple-05:80;
#      proxy_set_header Host $host;
#      add_header 'Access-Control-Allow-Origin' '*' always;
#    }
#  }
#}
