events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name mydomain.me
    
    location /.a-route {
      proxy_pass http://a-container-in-ingress-network:80;
      proxy_set_header Host $host;
    }
  }
}

