version: '3.8'

services:
  bitcoind:
    extends:
      file: bitcoind/docker-compose.yml
      service: bitcoind

  lnd:
    extends:
      file: lnd/docker-compose.yml
      service: lnd

  nginx-proxy:
    extends:
      file: nginx-proxy/docker-compose.yml
      service: nginx-proxy
    networks:
      - ingress

  nipple-05:
    extends:
      file: nipple-05/docker-compose.yml
      service: nipple-05
    networks:
      - ingress

volumes:
  bitcoin:
    driver: local

  lnd:
    driver: local

networks:
  bitcoin:
    driver: bridge
  ingress:
    driver: bridge

