version: '3'
services:
    bitcoind:
      image: bitcoind
      container_name: bitcoind
      build:
        context: bitcoind/
      volumes:
        - bitcoin:/data
      environment:
        - RPCAUTH
        - NETWORK
        - BITCOIND_DEBUG
      entrypoint: ["./start.sh"]

    lnd:
      image: lnd
      container_name: lnd
      build:
        context: lnd/
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - CHAIN
        - LND_DEBUG
        - BACKEND=bitcoind
      volumes:
        - lnd:/root/.lnd
      entrypoint: ["./start-lnd.sh"]
      links:
        - "bitcoind:blockchain"

volumes:
  bitcoin:
    driver: local

  lnd:
    driver: local
