version: '3'

services:
  bitcoind:
    extends:
      file: bitcoind/docker-compose.yml
      service: bitcoind

  lnd:
    extends:
      file: lnd/docker-compose.yml
      service: lnd

volumes:
  bitcoin:
    driver: local

  lnd:
    driver: local
