version: '3'
services:
    bitcoind:
      image: bitcoind${ENV_SUFFIX}
      container_name: bitcoind${ENV_SUFFIX}
      build:
        context: ./
      volumes:
        - bitcoin:/data
      entrypoint: ["./start.sh"]
      networks:
        - bitcoin
