version: '3'
services:
    bitcoind:
      image: bitcoind
      container_name: bitcoind
      build:
        context: ./
      volumes:
        - bitcoin:/data
      entrypoint: ["./start.sh"]
      networks:
        - bitcoin
