services:
  lnd:
    image: lnd${ENV_SUFFIX}
    container_name: lnd${ENV_SUFFIX}
    build:
      context: ./
    volumes:
      - bitcoin:/data
    entrypoint: ["./start.sh"]
    networks:
      - bitcoin
