version: '3'
services:
    lnd:
      image: lnd
      container_name: lnd
      build:
        context: ./
      volumes:
        - lnd:/root/.lnd
        - bitcoin:/data
      entrypoint: ["./start.sh"]
