bitcoin.node=bitcoind
bitcoin.testnet4=1
debuglevel=info
noseedbackup=1
rpclisten=lnd:10009

[Bitcoind]
bitcoind.dir=/data
bitcoind.rpccookie=/data/testnet4/.cookie
bitcoind.rpchost=bitcoind:8332
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333
