services:
  ord:
    image: ord${ENV_SUFFIX}
    container_name: ord${ENV_SUFFIX}
    build:
      context: ./
    volumes:
      - bitcoin:/data
    entrypoint: ["./start.sh"]
    networks:
      - bitcoin
